services:
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle_container
    environment:
      ORACLE_PASSWORD: ${APPLICATION_PASSWORD_SENTIMENT_ANALISYS}
      APP_USER: ${DOCKER-COMPOSE_APP_USER_SENTIMENT_ANALISYS}
      APP_USER_PASSWORD: ${DOCKER-COMPOSE_APP_USER_PASSWORD_SENTIMENT_ANALISYS}
    ports:
      - "1522:1522"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      API_PYTHON_URL: http://host.docker.internal:8000
      SPRING_DATASOURCE_URL: ${APPLICATION-ORACLEXE_URL_SENTIMENT_ANALISYS}
      SPRING_DATASOURCE_USERNAME: ${APPLICATION-ORACLEXE_USERNAME_SENTIMENT_ANALISYS}
      SPRING_DATASOURCE_PASSWORD: ${APPLICATION_PASSWORD_SENTIMENT_ANALISYS}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect