# Configuracao do Oracle XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${APPLICATION-ORACLEXE_URL_SENTIMENT_ANALISYS}
spring.datasource.username=${APPLICATION-ORACLEXE_USERNAME_SENTIMENT_ANALISYS}
spring.datasource.password=${APPLICATION_PASSWORD_SENTIMENT_ANALISYS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true