spring.datasource.url=jdbc:postgresql://shortline.proxy.rlwy.net:25032/railway
spring.datasource.username=postgres
spring.datasource.password=aoMhqEYiVixijHUaPdbmFKCBCaSBriDQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
