spring.datasource.url=${APPLICATION_POSTGRESQL_URL_SENTIMENT_ANALISYS}
spring.datasource.username=${APPLICATION_POSTGRESQL_USERNAME_SENTIMENT_ANALISYS}
spring.datasource.password=${APPLICATION_POSTGRESQL_PASSWORD_SENTIMENT_ANALISYS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true