apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: meuapp:1.0   # use sua imagem carregada no Kind
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:oracle:thin:@oracle-service:1521/XEPDB1
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.Oracle12cDialect
